//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int P_Id { get; set; }
        [Display(Name ="Product Name")]
        public string P_Name { get; set; }

        [Display(Name ="Product Price")]
        public Nullable<int> P_Price { get; set; }

        [Display(Name = "Quantity")]
        public Nullable<int> P_Quantity { get; set; }

        [Display(Name = "Image")]
        public string P_Image { get; set; }

        [Display(Name = "Category ID:")]
        public Nullable<int> CatID_FK { get; set; }

        //public HttpPostedFileBase ImageFile { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
